name: Deploy to Render.com

on:
  push:
    branches:
      - master  # You can change this to your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Debug Secrets
        run: |
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}"
          echo "DOCKERHUB_TOKEN length=${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Set your Docker Hub username as a secret
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  # Set your Docker Hub password as a secret

      - name: Build and Push Docker Image
        run: |
          docker build -t nurlancreus/mini-ecommerce:latest .
          docker push nurlancreus/mini-ecommerce:latest


      - name: Trigger Render Deployment
        run: curl -X POST -d '{}' ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
